name: AsciiDoc to PDF

on: push

jobs:
  asciidoc_to_pdf:
    name: AsciiDoc to PDF
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install AsciiDoctor PDF
        run: gem install asciidoctor-pdf --pre
      - name: Install required dependencies
        run: gem install rouge
      - name: Convert AsciiDoc to PDF
        run: asciidoctor-pdf README.adoc
      - name: Rename generated PDF
        run: mv README.pdf python2nodemcu.pdf
      - name: Publish PDF to Release Artifacts
        uses: actions/upload-artifact@master
        with:
          name: python2nodemcu
          path: python2nodemcu.pdf
      - name: Publish PDF to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: python2nodemcu.pdf
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
